# Generated by Django 6.0.4 on 2026-04-16 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('geo', '0002_alter_cercle_code_alter_cercle_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
        migrations.AddField(
            model_name='user',
            name='cercle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='geo.cercle'),
        ),
        migrations.AddField(
            model_name='user',
            name='commune',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='geo.commune'),
        ),
        migrations.AddField(
            model_name='user',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='geo.region'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrateur'), ('SUPERVISOR', 'Superviseur'), ('PROGRAM_MANAGER', 'Programme Manager'), ('TECH_VALIDATOR', 'Validateur technique'), ('DATA_ENTRY', 'Agent de saisie'), ('VIEWER', 'Lecteur')], default='VIEWER', max_length=30),
        ),
    ]
