# Generated by Django 6.0.4 on 2026-05-06 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_account_locked_until_user_created_at_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('geo', '0003_cercle_latitude_cercle_longitude_commune_latitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LAMHAccessGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_access_accidents', models.BooleanField(default=True)),
                ('can_access_victims', models.BooleanField(default=True)),
                ('can_access_eree', models.BooleanField(default=True)),
                ('can_access_reporting', models.BooleanField(default=False)),
                ('can_view_all_regions', models.BooleanField(default=False, verbose_name='Accès à toutes les régions')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cercles', models.ManyToManyField(blank=True, to='geo.cercle', verbose_name='Cercles autorisés')),
                ('communes', models.ManyToManyField(blank=True, to='geo.commune', verbose_name='Communes autorisées')),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lamh_access', to='auth.group')),
                ('regions', models.ManyToManyField(blank=True, to='geo.region', verbose_name='Régions autorisées')),
            ],
        ),
    ]
