# Generated by Django 6.0.4 on 2026-05-06 14:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_lamhaccessgroup'),
        ('geo', '0003_cercle_latitude_cercle_longitude_commune_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lamhaccessgroup',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='lamh_access_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lamhaccessgroup',
            name='can_view_all_regions',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='lamhaccessgroup',
            name='cercles',
            field=models.ManyToManyField(blank=True, to='geo.cercle'),
        ),
        migrations.AlterField(
            model_name='lamhaccessgroup',
            name='communes',
            field=models.ManyToManyField(blank=True, to='geo.commune'),
        ),
        migrations.AlterField(
            model_name='lamhaccessgroup',
            name='regions',
            field=models.ManyToManyField(blank=True, to='geo.region'),
        ),
    ]
