# Generated by Django 6.0.4 on 2026-05-13 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_lamhaccessgroup_users_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrateur'), ('SUPERVISOR', 'Superviseur'), ('PROJECT_MANAGER', 'Project Manager'), ('TECH_VALIDATOR', 'Validateur technique'), ('TECH_VERIFIER', 'Verification technique'), ('DATA_ENTRY', 'Agent de saisie'), ('VIEWER', 'Lecteur')], default='VIEWER', max_length=30),
        ),
    ]
