# Generated by Django 6.0.2 on 2026-04-13 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('incidents', '0002_incident_is_synced_incident_kobo_asset_uid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Victim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kobo_submission_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Kobo Submission ID')),
                ('kobo_uuid', models.CharField(blank=True, max_length=255, null=True, verbose_name='Kobo UUID')),
                ('raw_payload', models.JSONField(blank=True, null=True, verbose_name='Payload brut Kobo')),
                ('first_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Prénom')),
                ('last_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nom')),
                ('age', models.PositiveIntegerField(blank=True, null=True, verbose_name='Âge')),
                ('age_group', models.CharField(choices=[('CHILD', 'Enfant'), ('ADULT', 'Adulte'), ('UNKNOWN', 'Inconnu')], default='UNKNOWN', max_length=20, verbose_name="Groupe d'âge")),
                ('sex', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin'), ('U', 'Inconnu')], default='U', max_length=1, verbose_name='Sexe')),
                ('status', models.CharField(choices=[('INJURED', 'Blessé'), ('KILLED', 'Décédé'), ('AFFECTED', 'Affecté'), ('UNKNOWN', 'Inconnu')], default='UNKNOWN', max_length=20, verbose_name='Statut')),
                ('occupation', models.CharField(blank=True, max_length=255, null=True, verbose_name='Occupation / activité')),
                ('activity_at_time', models.CharField(blank=True, max_length=255, null=True, verbose_name="Activité au moment de l'incident")),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('assistance_needed', models.TextField(blank=True, null=True, verbose_name='Assistance requise')),
                ('submitter_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email du soumissionnaire')),
                ('submitter_first_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Prénom du soumissionnaire')),
                ('submitter_last_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nom du soumissionnaire')),
                ('submitter_phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Téléphone du soumissionnaire')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('accident', models.ForeignKey(
    on_delete=django.db.models.deletion.CASCADE,
    related_name='victims',
    to='incidents.accident',
    verbose_name='Accident'
)),
            ],
            options={
                'verbose_name': 'Victime',
                'verbose_name_plural': 'Victimes',
                'ordering': ['incident', 'id'],
            },
        ),
    ]
