# Generated by Django 6.0.2 on 2026-04-14 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("incidents", "0003_remove_incident_cercle_remove_incident_commune_and_more"),
        ("victims", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="victim",
            old_name="incident",
            new_name="accident",
        ),
        migrations.AlterField(
            model_name="victim",
            name="activity_at_time",
            field=models.CharField(
                "Activité au moment de l'accident",
                max_length=255,
                blank=True,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="victim",
            name="accident",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="victims",
                to="incidents.accident",
                verbose_name="Accident",
            ),
        ),
        migrations.AlterModelOptions(
            name="victim",
            options={
                "ordering": ["accident", "id"],
                "verbose_name": "Victime",
                "verbose_name_plural": "Victimes",
            },
        ),
    ]