# Generated by Django 6.0.2 on 2026-04-15 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0001_initial'),
        ('victims', '0002_alter_victim_options_remove_victim_incident_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='victim',
            options={'ordering': ['victim_last_name', 'victim_first_name', 'id'], 'verbose_name': 'Victime', 'verbose_name_plural': 'Victimes'},
        ),
        migrations.RemoveField(
            model_name='victim',
            name='activity_at_time',
        ),
        migrations.RemoveField(
            model_name='victim',
            name='age',
        ),
        migrations.RemoveField(
            model_name='victim',
            name='age_group',
        ),
        migrations.RemoveField(
            model_name='victim',
            name='assistance_needed',
        ),
        migrations.RemoveField(
            model_name='victim',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='victim',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='victim',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='victim',
            name='occupation',
        ),
        migrations.RemoveField(
            model_name='victim',
            name='sex',
        ),
        migrations.RemoveField(
            model_name='victim',
            name='status',
        ),
        migrations.RemoveField(
            model_name='victim',
            name='submitter_email',
        ),
        migrations.RemoveField(
            model_name='victim',
            name='submitter_first_name',
        ),
        migrations.RemoveField(
            model_name='victim',
            name='submitter_last_name',
        ),
        migrations.RemoveField(
            model_name='victim',
            name='submitter_phone',
        ),
        migrations.AddField(
            model_name='victim',
            name='accident_reference',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Référence de l'accident"),
        ),
        migrations.AddField(
            model_name='victim',
            name='activity_at_accident',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Activité au moment de l'accident"),
        ),
        migrations.AddField(
            model_name='victim',
            name='activity_at_accident_other',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Autre activité au moment de l'accident"),
        ),
        migrations.AddField(
            model_name='victim',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Adresse'),
        ),
        migrations.AddField(
            model_name='victim',
            name='alpc_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Type d'ALPC"),
        ),
        migrations.AddField(
            model_name='victim',
            name='alpc_type_other',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Autre type d'ALPC"),
        ),
        migrations.AddField(
            model_name='victim',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date de naissance'),
        ),
        migrations.AddField(
            model_name='victim',
            name='birth_date_approx',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Date de naissance approximative'),
        ),
        migrations.AddField(
            model_name='victim',
            name='birth_date_known',
            field=models.BooleanField(default=False, verbose_name='Date de naissance connue'),
        ),
        migrations.AddField(
            model_name='victim',
            name='blast_cause',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Cause de l'explosion"),
        ),
        migrations.AddField(
            model_name='victim',
            name='blast_cause_other',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Autre cause'),
        ),
        migrations.AddField(
            model_name='victim',
            name='cercle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='victim_reports', to='geo.cercle'),
        ),
        migrations.AddField(
            model_name='victim',
            name='commune',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='victim_reports', to='geo.commune'),
        ),
        migrations.AddField(
            model_name='victim',
            name='consentement',
            field=models.BooleanField(default=True, verbose_name='Consentement'),
        ),
        migrations.AddField(
            model_name='victim',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Pays'),
        ),
        migrations.AddField(
            model_name='victim',
            name='dependents_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Personnes à charge'),
        ),
        migrations.AddField(
            model_name='victim',
            name='disability_type_before',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Type de handicap avant l'accident"),
        ),
        migrations.AddField(
            model_name='victim',
            name='er_after_date',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Date approximative ER après'),
        ),
        migrations.AddField(
            model_name='victim',
            name='er_before_date',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Date approximative ER avant'),
        ),
        migrations.AddField(
            model_name='victim',
            name='er_org',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Organisation ayant délivré la session ER'),
        ),
        migrations.AddField(
            model_name='victim',
            name='father_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nom du père'),
        ),
        migrations.AddField(
            model_name='victim',
            name='health_structure',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Structure de santé'),
        ),
        migrations.AddField(
            model_name='victim',
            name='health_structure_other',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Autre structure de santé'),
        ),
        migrations.AddField(
            model_name='victim',
            name='hours_to_first_medical_care',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Temps avant première prise en charge médicale (heures)'),
        ),
        migrations.AddField(
            model_name='victim',
            name='info_source',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Source d'information"),
        ),
        migrations.AddField(
            model_name='victim',
            name='info_source_other',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Autre source'),
        ),
        migrations.AddField(
            model_name='victim',
            name='injury_description',
            field=models.TextField(blank=True, null=True, verbose_name='Description de la blessure / du traumatisme'),
        ),
        migrations.AddField(
            model_name='victim',
            name='injury_type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Type de blessure / traumatisme'),
        ),
        migrations.AddField(
            model_name='victim',
            name='knew_danger_zone',
            field=models.BooleanField(default=False, verbose_name='Connaissait la zone dangereuse'),
        ),
        migrations.AddField(
            model_name='victim',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='victim',
            name='location_details',
            field=models.TextField(blank=True, null=True, verbose_name="Détails de l'emplacement"),
        ),
        migrations.AddField(
            model_name='victim',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude'),
        ),
        migrations.AddField(
            model_name='victim',
            name='loss_of',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Perte de'),
        ),
        migrations.AddField(
            model_name='victim',
            name='main_breadwinner',
            field=models.BooleanField(default=False, verbose_name='Principal soutien de famille'),
        ),
        migrations.AddField(
            model_name='victim',
            name='marital_status',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Statut matrimonial'),
        ),
        migrations.AddField(
            model_name='victim',
            name='medical_care',
            field=models.BooleanField(default=False, verbose_name='Prise en charge médicale'),
        ),
        migrations.AddField(
            model_name='victim',
            name='medical_care_date',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Date approximative prise en charge médicale'),
        ),
        migrations.AddField(
            model_name='victim',
            name='medical_org',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Organisation prise en charge médicale'),
        ),
        migrations.AddField(
            model_name='victim',
            name='mother_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nom de la mère'),
        ),
        migrations.AddField(
            model_name='victim',
            name='nationality',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nationalité'),
        ),
        migrations.AddField(
            model_name='victim',
            name='nationality_other',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Autre nationalité'),
        ),
        migrations.AddField(
            model_name='victim',
            name='no_consent_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Raison du non consentement'),
        ),
        migrations.AddField(
            model_name='victim',
            name='non_medical_care',
            field=models.BooleanField(default=False, verbose_name='Prise en charge non médicale'),
        ),
        migrations.AddField(
            model_name='victim',
            name='non_medical_care_date',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Date approximative prise en charge non médicale'),
        ),
        migrations.AddField(
            model_name='victim',
            name='non_medical_org',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Organisation prise en charge non médicale'),
        ),
        migrations.AddField(
            model_name='victim',
            name='outcome_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tué / Blessé / impacté'),
        ),
        migrations.AddField(
            model_name='victim',
            name='pre_existing_disability',
            field=models.BooleanField(default=False, verbose_name="Handicap avant l'accident"),
        ),
        migrations.AddField(
            model_name='victim',
            name='profession_after',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Profession après l'accident"),
        ),
        migrations.AddField(
            model_name='victim',
            name='profession_after_other',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Préciser profession après'),
        ),
        migrations.AddField(
            model_name='victim',
            name='profession_before',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Profession avant l'accident"),
        ),
        migrations.AddField(
            model_name='victim',
            name='profession_before_other',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Préciser profession avant'),
        ),
        migrations.AddField(
            model_name='victim',
            name='reason_enter_zone',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Raison d'entrer dans la zone"),
        ),
        migrations.AddField(
            model_name='victim',
            name='reason_enter_zone_other',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Autre raison d'entrée"),
        ),
        migrations.AddField(
            model_name='victim',
            name='received_er_after',
            field=models.BooleanField(default=False, verbose_name="A reçu une session ER après l'accident"),
        ),
        migrations.AddField(
            model_name='victim',
            name='received_er_before',
            field=models.BooleanField(default=False, verbose_name="A reçu une session ER avant l'accident"),
        ),
        migrations.AddField(
            model_name='victim',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='victim_reports', to='geo.region'),
        ),
        migrations.AddField(
            model_name='victim',
            name='report_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date du rapport'),
        ),
        migrations.AddField(
            model_name='victim',
            name='reported_by',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Rapporté par'),
        ),
        migrations.AddField(
            model_name='victim',
            name='reporting_org',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Organisation'),
        ),
        migrations.AddField(
            model_name='victim',
            name='reporting_position',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Poste'),
        ),
        migrations.AddField(
            model_name='victim',
            name='reporting_team',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Equipe'),
        ),
        migrations.AddField(
            model_name='victim',
            name='residence_place',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Lieu de résidence'),
        ),
        migrations.AddField(
            model_name='victim',
            name='saw_object',
            field=models.BooleanField(default=False, verbose_name="A vu l'objet"),
        ),
        migrations.AddField(
            model_name='victim',
            name='source_age',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Age de la source'),
        ),
        migrations.AddField(
            model_name='victim',
            name='source_contact',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Contact de la source'),
        ),
        migrations.AddField(
            model_name='victim',
            name='source_first_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Prénom de la source'),
        ),
        migrations.AddField(
            model_name='victim',
            name='source_last_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nom de la source'),
        ),
        migrations.AddField(
            model_name='victim',
            name='source_sex',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Sexe de la source'),
        ),
        migrations.AddField(
            model_name='victim',
            name='times_entered_zone',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Nombre de fois entrée dans la zone'),
        ),
        migrations.AddField(
            model_name='victim',
            name='urgent_medical_evac',
            field=models.BooleanField(default=False, verbose_name="Besoin d'évacuation / prise en charge médicale immédiate"),
        ),
        migrations.AddField(
            model_name='victim',
            name='victim_age',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Âge'),
        ),
        migrations.AddField(
            model_name='victim',
            name='victim_contact',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Contact'),
        ),
        migrations.AddField(
            model_name='victim',
            name='victim_first_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Prénom de la victime'),
        ),
        migrations.AddField(
            model_name='victim',
            name='victim_id',
            field=models.CharField(default='', max_length=100, unique=True, verbose_name='ID de la victime'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='victim',
            name='victim_last_name',
            field=models.CharField(default='', max_length=150, verbose_name='Nom de la victime'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='victim',
            name='victim_sex',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Sexe'),
        ),
        migrations.AddField(
            model_name='victim',
            name='victim_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Type de victime'),
        ),
        migrations.AddField(
            model_name='victim',
            name='victim_type_other',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Préciser type de victime'),
        ),
        migrations.AddField(
            model_name='victim',
            name='village_quartier',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Village / Quartier'),
        ),
    ]
