# Generated by Django 6.0.2 on 2026-04-15 13:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('victims', '0003_alter_victim_options_remove_victim_activity_at_time_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='victim',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Approuvé le'),
        ),
        migrations.AddField(
            model_name='victim',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_approved', to=settings.AUTH_USER_MODEL, verbose_name='Approuvé par'),
        ),
        migrations.AddField(
            model_name='victim',
            name='correction_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Commentaire de correction'),
        ),
        migrations.AddField(
            model_name='victim',
            name='program_validated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Validé programme le'),
        ),
        migrations.AddField(
            model_name='victim',
            name='program_validated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_program_validated', to=settings.AUTH_USER_MODEL, verbose_name='Validé programme par'),
        ),
        migrations.AddField(
            model_name='victim',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Motif de rejet'),
        ),
        migrations.AddField(
            model_name='victim',
            name='status',
            field=models.CharField(choices=[('SUBMITTED', 'Soumis'), ('TECH_VALIDATED', 'Validé technique'), ('TECH_REJECTED', 'Rejeté technique'), ('PROGRAM_VALIDATED', 'Validé programme'), ('PROGRAM_REJECTED', 'Rejeté programme'), ('RETURNED_FOR_CORRECTION', 'Retourné pour correction'), ('APPROVED', 'Approuvé')], db_index=True, default='SUBMITTED', max_length=30, verbose_name='Statut de validation'),
        ),
        migrations.AddField(
            model_name='victim',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Soumis le'),
        ),
        migrations.AddField(
            model_name='victim',
            name='tech_validated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Validé techniquement le'),
        ),
        migrations.AddField(
            model_name='victim',
            name='tech_validated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_tech_validated', to=settings.AUTH_USER_MODEL, verbose_name='Validé techniquement par'),
        ),
    ]
