# Generated by Django 6.0.4 on 2026-04-22 14:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('victims', '0004_victim_approved_at_victim_approved_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VictimChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workflow_step', models.CharField(blank=True, max_length=100, null=True)),
                ('field_name', models.CharField(max_length=255)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('victim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_logs', to='victims.victim')),
            ],
            options={
                'verbose_name': 'Historique victime',
                'verbose_name_plural': 'Historiques victimes',
                'ordering': ['-changed_at'],
            },
        ),
    ]
