# Generated by Django 6.0.4 on 2026-05-08 11:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('victims', '0005_victimchangelog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='victim',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='victim',
            name='correction_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='victim',
            name='program_validated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_program_validated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='victim',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='victim',
            name='tech_validated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_tech_validated', to=settings.AUTH_USER_MODEL),
        ),
    ]
