# Generated by Django 6.0.4 on 2026-05-13 21:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('victims', '0006_alter_victim_approved_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='victim',
            name='tech_verified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Vérifié techniquement le'),
        ),
        migrations.AddField(
            model_name='victim',
            name='tech_verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_tech_verified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='victim',
            name='validation_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='victim',
            name='status',
            field=models.CharField(choices=[('SUBMITTED', 'Soumis'), ('TECH_VERIFIED', 'Vérification technique'), ('TECH_VALIDATED', 'Validation technique'), ('PROGRAM_VALIDATED', 'Validation programme'), ('RETURNED_FOR_CORRECTION', 'Retourné pour correction'), ('APPROVED', 'Approuvé')], db_index=True, default='SUBMITTED', max_length=40, verbose_name='Statut de validation'),
        ),
    ]
