# Generated by Django 6.0.4 on 2026-05-07 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paiassistancesubmission',
            name='assistance_type',
        ),
        migrations.RemoveField(
            model_name='paiassistancesubmission',
            name='victim_code',
        ),
        migrations.RemoveField(
            model_name='paiassistancesubmission',
            name='victim_name',
        ),
        migrations.AlterField(
            model_name='paiassistancesubmission',
            name='raw_data',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
