# Generated by Django 6.0.4 on 2026-05-07 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0002_remove_paiassistancesubmission_assistance_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiassistancesubmission',
            name='assistance_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='paiassistancesubmission',
            name='victim_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='paiassistancesubmission',
            name='victim_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='paiassistancesubmission',
            name='raw_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
