# Generated by Django 6.0.4 on 2026-04-23 09:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geo', '0002_alter_cercle_code_alter_cercle_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EREESession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=50, unique=True, verbose_name='Référence')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Titre')),
                ('activity_date', models.DateField(verbose_name="Date de l'activité")),
                ('activity_type', models.CharField(choices=[('COMMUNITY', 'Sensibilisation communautaire'), ('SCHOOL', 'Activité scolaire'), ('MASS_MEDIA', 'Média / Radio'), ('DOOR_TO_DOOR', 'Porte à porte'), ('OTHER', 'Autre')], default='OTHER', max_length=50, verbose_name="Type d'activité")),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('locality', models.CharField(blank=True, max_length=255, null=True, verbose_name='Localité / Village')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude')),
                ('organization', models.CharField(blank=True, max_length=255, null=True, verbose_name='Organisation')),
                ('facilitator_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nom du facilitateur')),
                ('men', models.PositiveIntegerField(default=0, verbose_name='Hommes')),
                ('women', models.PositiveIntegerField(default=0, verbose_name='Femmes')),
                ('boys', models.PositiveIntegerField(default=0, verbose_name='Garçons')),
                ('girls', models.PositiveIntegerField(default=0, verbose_name='Filles')),
                ('total_participants', models.PositiveIntegerField(default=0, verbose_name='Total participants')),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('SUBMITTED', 'Soumis'), ('TECH_VALIDATED', 'Validé techniquement'), ('PROGRAM_VALIDATED', 'Validé programme'), ('APPROVED', 'Approuvé')], default='DRAFT', max_length=30, verbose_name='Statut')),
                ('validation_comment', models.TextField(blank=True, null=True, verbose_name='Commentaire de validation')),
                ('rejection_reason', models.TextField(blank=True, null=True, verbose_name='Motif de rejet')),
                ('correction_comment', models.TextField(blank=True, null=True, verbose_name='Commentaire de correction')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Soumis le')),
                ('tech_validated_at', models.DateTimeField(blank=True, null=True, verbose_name='Validé techniquement le')),
                ('program_validated_at', models.DateTimeField(blank=True, null=True, verbose_name='Validé programme le')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Approuvé le')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eree_approved', to=settings.AUTH_USER_MODEL, verbose_name='Approuvé par')),
                ('cercle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eree_sessions', to='geo.cercle', verbose_name='Cercle')),
                ('commune', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eree_sessions', to='geo.commune', verbose_name='Commune')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eree_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('program_validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eree_program_validated', to=settings.AUTH_USER_MODEL, verbose_name='Validé programme par')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eree_sessions', to='geo.region', verbose_name='Région')),
                ('tech_validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eree_tech_validated', to=settings.AUTH_USER_MODEL, verbose_name='Validé techniquement par')),
            ],
            options={
                'verbose_name': 'Activité EREE',
                'verbose_name_plural': 'Activités EREE',
                'ordering': ['-activity_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EREESessionChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workflow_step', models.CharField(blank=True, max_length=50)),
                ('field_name', models.CharField(max_length=100)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_logs', to='eree.ereesession')),
            ],
            options={
                'verbose_name': 'EREE change log',
                'verbose_name_plural': 'EREE change logs',
                'ordering': ['-changed_at'],
            },
        ),
    ]
