# Generated by Django 6.0.4 on 2026-04-23 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eree', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ereesession',
            name='kobo_submission_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Kobo Submission ID'),
        ),
        migrations.AddField(
            model_name='ereesession',
            name='kobo_uuid',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Kobo UUID'),
        ),
        migrations.AddField(
            model_name='ereesession',
            name='raw_payload',
            field=models.JSONField(blank=True, null=True, verbose_name='Payload brut Kobo'),
        ),
        migrations.AddField(
            model_name='ereesession',
            name='submitted_at_kobo',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Soumis dans Kobo le'),
        ),
    ]
