# Generated by Django 6.0.4 on 2026-04-23 14:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eree', '0003_remove_ereesession_boys_and_more'),
        ('geo', '0002_alter_cercle_code_alter_cercle_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ereesession',
            options={'ordering': ['-session_date', '-created_at'], 'verbose_name': 'Session EREE', 'verbose_name_plural': 'Sessions EREE'},
        ),
        migrations.RenameField(
            model_name='ereesession',
            old_name='organization',
            new_name='organisation',
        ),
        migrations.RemoveField(
            model_name='ereesession',
            name='activity_date',
        ),
        migrations.RemoveField(
            model_name='ereesession',
            name='activity_type',
        ),
        migrations.RemoveField(
            model_name='ereesession',
            name='description',
        ),
        migrations.RemoveField(
            model_name='ereesession',
            name='locality',
        ),
        migrations.AddField(
            model_name='ereesession',
            name='cercle_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Code cercle Kobo'),
        ),
        migrations.AddField(
            model_name='ereesession',
            name='commune_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Code commune Kobo'),
        ),
        migrations.AddField(
            model_name='ereesession',
            name='region_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Code région Kobo'),
        ),
        migrations.AddField(
            model_name='ereesession',
            name='session_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date session'),
        ),
        migrations.AddField(
            model_name='ereesession',
            name='village',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Village'),
        ),
        migrations.AlterField(
            model_name='ereesession',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eree_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ereesession',
            name='cercle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='eree_sessions', to='geo.cercle', verbose_name='Cercle'),
        ),
        migrations.AlterField(
            model_name='ereesession',
            name='civilian_subcategory',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Sous-catégorie civils'),
        ),
        migrations.AlterField(
            model_name='ereesession',
            name='commune',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='eree_sessions', to='geo.commune', verbose_name='Commune'),
        ),
        migrations.AlterField(
            model_name='ereesession',
            name='correction_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Commentaire correction'),
        ),
        migrations.AlterField(
            model_name='ereesession',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ereesession',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eree_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ereesession',
            name='difficulties_solutions',
            field=models.TextField(blank=True, null=True, verbose_name='Difficultés / solutions'),
        ),
        migrations.AlterField(
            model_name='ereesession',
            name='humanitarian_female',
            field=models.PositiveIntegerField(default=0, verbose_name='Humanitaire femmes'),
        ),
        migrations.AlterField(
            model_name='ereesession',
            name='humanitarian_male',
            field=models.PositiveIntegerField(default=0, verbose_name='Humanitaire hommes'),
        ),
        migrations.AlterField(
            model_name='ereesession',
            name='humanitarian_org_type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Type organisation humanitaire'),
        ),
        migrations.AlterField(
            model_name='ereesession',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='ereesession',
            name='location_gps',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Coordonnées GPS'),
        ),
        migrations.AlterField(
            model_name='ereesession',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='ereesession',
            name='narrative_description',
            field=models.TextField(blank=True, null=True, verbose_name='Description narrative'),
        ),
        migrations.AlterField(
            model_name='ereesession',
            name='program_validated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eree_program_validated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ereesession',
            name='reference',
            field=models.CharField(max_length=100, unique=True, verbose_name='Référence'),
        ),
        migrations.AlterField(
            model_name='ereesession',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='eree_sessions', to='geo.region', verbose_name='Région'),
        ),
        migrations.AlterField(
            model_name='ereesession',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Motif rejet'),
        ),
        migrations.AlterField(
            model_name='ereesession',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Brouillon'), ('SUBMITTED', 'Soumis'), ('TECH_VALIDATED', 'Validé techniquement'), ('PROGRAM_VALIDATED', 'Validé programme'), ('APPROVED', 'Approuvé')], default='DRAFT', max_length=30, verbose_name='Statut workflow'),
        ),
        migrations.AlterField(
            model_name='ereesession',
            name='tech_validated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eree_tech_validated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ereesession',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='ereesession',
            name='validation_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Commentaire validation'),
        ),
    ]
