# Generated by Django 6.0.4 on 2026-05-08 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eree', '0004_alter_ereesession_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ereesession',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Brouillon'), ('SUBMITTED', 'Soumis'), ('TECH_VALIDATED', 'Validé techniquement'), ('PROGRAM_VALIDATED', 'Validé programme'), ('RETURNED_FOR_CORRECTION', 'Retourné pour correction'), ('APPROVED', 'Approuvé')], default='DRAFT', max_length=30, verbose_name='Statut workflow'),
        ),
    ]
