# Generated by Django 6.0.4 on 2026-05-13 21:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eree', '0005_alter_ereesession_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ereesession',
            name='tech_verified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Vérifié techniquement le'),
        ),
        migrations.AddField(
            model_name='ereesession',
            name='tech_verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_tech_verified', to=settings.AUTH_USER_MODEL),
        ),
    ]
