# Generated by Django 6.0.4 on 2026-05-16 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eree', '0006_ereesession_tech_verified_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EREEDisaggregation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_group', models.CharField(choices=[('0_5', '0-5 ans'), ('6_14', '6-14 ans'), ('15_17', '15-17 ans'), ('18_24', '18-24 ans'), ('25_49', '25-49 ans'), ('50_59', '50-59 ans'), ('60_plus', '60+ ans')], max_length=20)),
                ('boys', models.PositiveIntegerField(default=0)),
                ('boys_disabled', models.PositiveIntegerField(default=0)),
                ('men', models.PositiveIntegerField(default=0)),
                ('men_disabled', models.PositiveIntegerField(default=0)),
                ('girls', models.PositiveIntegerField(default=0)),
                ('girls_disabled', models.PositiveIntegerField(default=0)),
                ('women', models.PositiveIntegerField(default=0)),
                ('women_disabled', models.PositiveIntegerField(default=0)),
                ('eree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disaggregations', to='eree.ereesession')),
            ],
        ),
    ]
