# Generated by Django 6.0.2 on 2026-04-15 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cercle',
            name='code',
            field=models.CharField(max_length=20, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='cercle',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='cercle',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cercles', to='geo.region', verbose_name='Région'),
        ),
        migrations.AlterField(
            model_name='commune',
            name='cercle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communes', to='geo.cercle', verbose_name='Cercle'),
        ),
        migrations.AlterField(
            model_name='commune',
            name='code',
            field=models.CharField(max_length=20, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='commune',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='region',
            name='code',
            field=models.CharField(max_length=20, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Nom'),
        ),
    ]
