# Generated by Django 6.0.2 on 2026-04-13 11:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=50, unique=True, verbose_name='Référence')),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('description', models.TextField(verbose_name='Description')),
                ('incident_date', models.DateField(verbose_name="Date de l'incident")),
                ('incident_time', models.TimeField(blank=True, null=True, verbose_name="Heure de l'incident")),
                ('category', models.CharField(choices=[('MINE', 'Mine'), ('ERW', 'ERW / UXO'), ('IED', 'IED'), ('BATTLE_AREA', 'Zone de combat contaminée'), ('OTHER', 'Autre')], max_length=30, verbose_name='Catégorie')),
                ('impact', models.CharField(choices=[('NONE', 'Aucun'), ('INJURY', 'Blessure'), ('DEATH', 'Décès'), ('DAMAGE', 'Dommages matériels'), ('MULTIPLE', 'Impacts multiples')], default='NONE', max_length=20, verbose_name='Impact principal')),
                ('locality', models.CharField(blank=True, max_length=255, null=True, verbose_name='Localité / Village')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude')),
                ('number_killed', models.PositiveIntegerField(default=0, verbose_name='Nombre de décès')),
                ('number_injured', models.PositiveIntegerField(default=0, verbose_name='Nombre de blessés')),
                ('number_affected', models.PositiveIntegerField(default=0, verbose_name='Nombre de personnes affectées')),
                ('source_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Source / Rapporté par')),
                ('source_contact', models.CharField(blank=True, max_length=100, null=True, verbose_name='Contact source')),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('SUBMITTED', 'Soumis'), ('VALIDATED', 'Validé'), ('REJECTED', 'Rejeté')], default='DRAFT', max_length=20, verbose_name='Statut')),
                ('validation_comment', models.TextField(blank=True, null=True, verbose_name='Commentaire de validation')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('validated_at', models.DateTimeField(blank=True, null=True, verbose_name='Validé le')),
                ('cercle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incidents', to='geo.cercle', verbose_name='Cercle')),
                ('commune', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incidents', to='geo.commune', verbose_name='Commune')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incidents', to='geo.region', verbose_name='Région')),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents_validated', to=settings.AUTH_USER_MODEL, verbose_name='Validé par')),
            ],
            options={
                'verbose_name': 'Incident',
                'verbose_name_plural': 'Incidents',
                'ordering': ['-incident_date', '-created_at'],
            },
        ),
    ]
