# Generated by Django 6.0.2 on 2026-04-13 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='is_synced',
            field=models.BooleanField(default=False, verbose_name='Synchronisé'),
        ),
        migrations.AddField(
            model_name='incident',
            name='kobo_asset_uid',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Kobo Asset UID'),
        ),
        migrations.AddField(
            model_name='incident',
            name='kobo_submission_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Kobo Submission ID'),
        ),
        migrations.AddField(
            model_name='incident',
            name='kobo_uuid',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Kobo UUID'),
        ),
        migrations.AddField(
            model_name='incident',
            name='raw_payload',
            field=models.JSONField(blank=True, null=True, verbose_name='Payload brut Kobo'),
        ),
        migrations.AddField(
            model_name='incident',
            name='source',
            field=models.CharField(choices=[('KOBO', 'Kobo'), ('MANUAL', 'Saisie manuelle'), ('API', 'API')], default='KOBO', max_length=20, verbose_name='Source'),
        ),
        migrations.AddField(
            model_name='incident',
            name='submitted_at_kobo',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Soumis dans Kobo le'),
        ),
        migrations.AddField(
            model_name='incident',
            name='submitter_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email du soumissionnaire'),
        ),
        migrations.AddField(
            model_name='incident',
            name='submitter_first_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Prénom du soumissionnaire'),
        ),
        migrations.AddField(
            model_name='incident',
            name='submitter_last_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nom du soumissionnaire'),
        ),
        migrations.AddField(
            model_name='incident',
            name='submitter_organization',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Organisation du soumissionnaire'),
        ),
        migrations.AddField(
            model_name='incident',
            name='submitter_phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Téléphone du soumissionnaire'),
        ),
        migrations.AddField(
            model_name='incident',
            name='submitter_role',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Fonction du soumissionnaire'),
        ),
        migrations.AddField(
            model_name='incident',
            name='submitter_username',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Username Kobo / identifiant'),
        ),
        migrations.AddField(
            model_name='incident',
            name='synced_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Synchronisé le'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='source_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Source / rapporté par'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Brouillon'), ('SUBMITTED', 'Soumis'), ('UNDER_REVIEW', 'En revue'), ('VALIDATED', 'Validé'), ('REJECTED', 'Rejeté')], default='SUBMITTED', max_length=20, verbose_name='Statut'),
        ),
    ]
