# Generated by Django 6.0.2 on 2026-04-14 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("incidents", "0002_incident_is_synced_incident_kobo_asset_uid_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Incident",
            new_name="Accident",
        ),
        migrations.AlterModelOptions(
            name="accident",
            options={
                "verbose_name": "Accident",
                "verbose_name_plural": "Accidents",
                "ordering": ["-incident_date", "-created_at"],
            },
        ),
    ]