# Generated by Django 6.0.2 on 2026-04-14 11:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0001_initial'),
        ('incidents', '0003_remove_incident_cercle_remove_incident_commune_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='accident',
            name='cercle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accidents', to='geo.cercle', verbose_name='Cercle'),
        ),
        migrations.AlterField(
            model_name='accident',
            name='commune',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accidents', to='geo.commune', verbose_name='Commune'),
        ),
        migrations.AlterField(
            model_name='accident',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accidents_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AlterField(
            model_name='accident',
            name='incident_date',
            field=models.DateField(verbose_name="Date de l'accident"),
        ),
        migrations.AlterField(
            model_name='accident',
            name='incident_time',
            field=models.TimeField(blank=True, null=True, verbose_name="Heure de l'accident"),
        ),
        migrations.AlterField(
            model_name='accident',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accidents', to='geo.region', verbose_name='Région'),
        ),
        migrations.AlterField(
            model_name='accident',
            name='validated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accidents_validated', to=settings.AUTH_USER_MODEL, verbose_name='Validé par'),
        ),
    ]
