# Generated by Django 6.0.4 on 2026-04-15 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0006_alter_accident_options_remove_accident_validated_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accident',
            name='accident_associe_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ID accident associé'),
        ),
        migrations.AddField(
            model_name='accident',
            name='activity_at_time',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Activité au moment de l'accident"),
        ),
        migrations.AddField(
            model_name='accident',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Pays'),
        ),
        migrations.AddField(
            model_name='accident',
            name='device_marked',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Engin marqué'),
        ),
        migrations.AddField(
            model_name='accident',
            name='device_status',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Statut de l'engin"),
        ),
        migrations.AddField(
            model_name='accident',
            name='device_type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Type d'engin"),
        ),
        migrations.AddField(
            model_name='accident',
            name='funding_source',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Source de financement'),
        ),
        migrations.AddField(
            model_name='accident',
            name='location_gps',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Coordonnées GPS brutes'),
        ),
        migrations.AddField(
            model_name='accident',
            name='number_victims',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Nombre de victimes'),
        ),
        migrations.AddField(
            model_name='accident',
            name='org_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Organisation'),
        ),
        migrations.AddField(
            model_name='accident',
            name='other_damage',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Autres dommages'),
        ),
        migrations.AddField(
            model_name='accident',
            name='position',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Poste'),
        ),
        migrations.AddField(
            model_name='accident',
            name='report_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date du rapport'),
        ),
        migrations.AddField(
            model_name='accident',
            name='reported_by',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Rapporté par'),
        ),
        migrations.AddField(
            model_name='accident',
            name='secure_access',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Accès sécurisé'),
        ),
        migrations.AddField(
            model_name='accident',
            name='source_age',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Âge de la source'),
        ),
        migrations.AddField(
            model_name='accident',
            name='source_first_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Prénom de la source'),
        ),
        migrations.AddField(
            model_name='accident',
            name='source_gender',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Sexe de la source'),
        ),
        migrations.AddField(
            model_name='accident',
            name='source_last_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nom de la source'),
        ),
        migrations.AddField(
            model_name='accident',
            name='source_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Type de source'),
        ),
        migrations.AddField(
            model_name='accident',
            name='src_coordinates',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Source des coordonnées'),
        ),
        migrations.AddField(
            model_name='accident',
            name='team',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Équipe'),
        ),
    ]
