# Generated by Django 6.0.4 on 2026-04-20 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0008_accidentchangelog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accident',
            name='category',
            field=models.CharField(choices=[('ALPC', 'ALPC'), ('MINE', 'Mine'), ('ERW', 'ERW / UXO'), ('IED', 'IED'), ('ROAD', 'Road'), ('OTHER', 'Autre')], default='OTHER', max_length=20, verbose_name='Catégorie'),
        ),
    ]
