# Generated by Django 6.0.4 on 2026-04-20 09:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0002_alter_cercle_code_alter_cercle_name_and_more'),
        ('incidents', '0009_alter_accident_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accident',
            options={'ordering': ['-accident_date', '-created_at']},
        ),
        migrations.RemoveField(
            model_name='accident',
            name='source_name',
        ),
        migrations.AlterField(
            model_name='accident',
            name='accident_associe_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='accident',
            name='accident_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accident',
            name='activity_at_time',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='accident',
            name='category',
            field=models.CharField(choices=[('ALPC', 'ALPC'), ('MINE', 'Mine'), ('ERW', 'ERW / UXO'), ('IED', 'IED'), ('ROAD', 'Road'), ('OTHER', 'Autre')], default='OTHER', max_length=20, verbose_name="Type d'accident"),
        ),
        migrations.AlterField(
            model_name='accident',
            name='cercle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='geo.cercle'),
        ),
        migrations.AlterField(
            model_name='accident',
            name='commune',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='geo.commune'),
        ),
        migrations.AlterField(
            model_name='accident',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='accident',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='accident',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='accident',
            name='device_marked',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='accident',
            name='device_status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='accident',
            name='device_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='accident',
            name='funding_source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='accident',
            name='impact',
            field=models.CharField(blank=True, choices=[('NONE', 'Aucun'), ('INJURY', 'Blessure'), ('DEATH', 'Décès'), ('DAMAGE', 'Dommages matériels'), ('MULTIPLE', 'Impacts multiples')], max_length=20, null=True, verbose_name='Impact principal'),
        ),
        migrations.AlterField(
            model_name='accident',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='accident',
            name='locality',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='accident',
            name='location_gps',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='accident',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='accident',
            name='number_affected',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accident',
            name='number_injured',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accident',
            name='number_killed',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accident',
            name='number_victims',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accident',
            name='org_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='accident',
            name='other_damage',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='accident',
            name='position',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='accident',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='geo.region'),
        ),
        migrations.AlterField(
            model_name='accident',
            name='report_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accident',
            name='reported_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='accident',
            name='secure_access',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='accident',
            name='source_age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accident',
            name='source_contact',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='accident',
            name='source_first_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='accident',
            name='source_gender',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='accident',
            name='source_last_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='accident',
            name='source_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='accident',
            name='src_coordinates',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='accident',
            name='submitter_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='accident',
            name='submitter_first_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='accident',
            name='submitter_last_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='accident',
            name='submitter_organization',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='accident',
            name='submitter_phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='accident',
            name='submitter_role',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='accident',
            name='submitter_username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='accident',
            name='team',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='accident',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Titre'),
        ),
        migrations.AlterField(
            model_name='accident',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='accident',
            name='validated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accident',
            name='validation_comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
