# Generated by Django 6.0.4 on 2026-04-20 10:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0002_alter_cercle_code_alter_cercle_name_and_more'),
        ('incidents', '0010_alter_accident_options_remove_accident_source_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accident',
            options={'ordering': ['-accident_date', '-created_at'], 'verbose_name': 'Accident', 'verbose_name_plural': 'Accidents'},
        ),
        migrations.AddField(
            model_name='accident',
            name='source_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Source / rapporté par'),
        ),
        migrations.AlterField(
            model_name='accident',
            name='accident_associe_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ID accident associé'),
        ),
        migrations.AlterField(
            model_name='accident',
            name='accident_time',
            field=models.TimeField(blank=True, null=True, verbose_name="Heure de l'accident"),
        ),
        migrations.AlterField(
            model_name='accident',
            name='activity_at_time',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Activité au moment de l'accident"),
        ),
        migrations.AlterField(
            model_name='accident',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accidents_approved', to=settings.AUTH_USER_MODEL, verbose_name='Approuvé par'),
        ),
        migrations.AlterField(
            model_name='accident',
            name='cercle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accidents', to='geo.cercle', verbose_name='Cercle'),
        ),
        migrations.AlterField(
            model_name='accident',
            name='commune',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accidents', to='geo.commune', verbose_name='Commune'),
        ),
        migrations.AlterField(
            model_name='accident',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Pays'),
        ),
        migrations.AlterField(
            model_name='accident',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Créé le'),
        ),
        migrations.AlterField(
            model_name='accident',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accidents_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AlterField(
            model_name='accident',
            name='device_marked',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Engin marqué'),
        ),
        migrations.AlterField(
            model_name='accident',
            name='device_status',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Statut de l'engin"),
        ),
        migrations.AlterField(
            model_name='accident',
            name='device_type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Type d'engin"),
        ),
        migrations.AlterField(
            model_name='accident',
            name='funding_source',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Source de financement'),
        ),
        migrations.AlterField(
            model_name='accident',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='accident',
            name='locality',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Localité / Village'),
        ),
        migrations.AlterField(
            model_name='accident',
            name='location_gps',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Coordonnées GPS brutes'),
        ),
        migrations.AlterField(
            model_name='accident',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='accident',
            name='number_affected',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Nombre de personnes affectées'),
        ),
        migrations.AlterField(
            model_name='accident',
            name='number_injured',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Nombre de blessés'),
        ),
        migrations.AlterField(
            model_name='accident',
            name='number_killed',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Nombre de décès'),
        ),
        migrations.AlterField(
            model_name='accident',
            name='number_victims',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Nombre de victimes'),
        ),
        migrations.AlterField(
            model_name='accident',
            name='org_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Organisation'),
        ),
        migrations.AlterField(
            model_name='accident',
            name='other_damage',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Autres dommages'),
        ),
        migrations.AlterField(
            model_name='accident',
            name='position',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Poste'),
        ),
        migrations.AlterField(
            model_name='accident',
            name='program_validated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accidents_program_validated', to=settings.AUTH_USER_MODEL, verbose_name='Validé programme par'),
        ),
        migrations.AlterField(
            model_name='accident',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accidents', to='geo.region', verbose_name='Région'),
        ),
        migrations.AlterField(
            model_name='accident',
            name='report_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date du rapport'),
        ),
        migrations.AlterField(
            model_name='accident',
            name='reported_by',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Rapporté par'),
        ),
        migrations.AlterField(
            model_name='accident',
            name='secure_access',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Accès sécurisé'),
        ),
        migrations.AlterField(
            model_name='accident',
            name='source_age',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Âge de la source'),
        ),
        migrations.AlterField(
            model_name='accident',
            name='source_contact',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Contact source'),
        ),
        migrations.AlterField(
            model_name='accident',
            name='source_first_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Prénom de la source'),
        ),
        migrations.AlterField(
            model_name='accident',
            name='source_gender',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Sexe de la source'),
        ),
        migrations.AlterField(
            model_name='accident',
            name='source_last_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nom de la source'),
        ),
        migrations.AlterField(
            model_name='accident',
            name='source_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Type de source'),
        ),
        migrations.AlterField(
            model_name='accident',
            name='src_coordinates',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Source des coordonnées'),
        ),
        migrations.AlterField(
            model_name='accident',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Brouillon'), ('SUBMITTED', 'Soumis'), ('TECH_VALIDATED', 'Validé techniquement'), ('PROGRAM_VALIDATED', 'Validé programme'), ('APPROVED', 'Approuvé'), ('TECH_REJECTED', 'Rejeté techniquement'), ('PROGRAM_REJECTED', 'Rejeté programme'), ('RETURNED_FOR_CORRECTION', 'Retourné pour correction')], default='DRAFT', max_length=30, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='accident',
            name='submitter_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email du soumissionnaire'),
        ),
        migrations.AlterField(
            model_name='accident',
            name='submitter_first_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Prénom du soumissionnaire'),
        ),
        migrations.AlterField(
            model_name='accident',
            name='submitter_last_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nom du soumissionnaire'),
        ),
        migrations.AlterField(
            model_name='accident',
            name='submitter_organization',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Organisation du soumissionnaire'),
        ),
        migrations.AlterField(
            model_name='accident',
            name='submitter_phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Téléphone du soumissionnaire'),
        ),
        migrations.AlterField(
            model_name='accident',
            name='submitter_role',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Fonction du soumissionnaire'),
        ),
        migrations.AlterField(
            model_name='accident',
            name='submitter_username',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Username Kobo / identifiant'),
        ),
        migrations.AlterField(
            model_name='accident',
            name='team',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Équipe'),
        ),
        migrations.AlterField(
            model_name='accident',
            name='tech_validated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accidents_tech_validated', to=settings.AUTH_USER_MODEL, verbose_name='Validé techniquement par'),
        ),
        migrations.AlterField(
            model_name='accident',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Mis à jour le'),
        ),
        migrations.AlterField(
            model_name='accident',
            name='validated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Validé le'),
        ),
        migrations.AlterField(
            model_name='accident',
            name='validation_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Commentaire de validation'),
        ),
    ]
