# Generated by Django 6.0.4 on 2026-04-20 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0011_alter_accident_options_accident_source_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accident',
            name='number_affected',
        ),
        migrations.RemoveField(
            model_name='accident',
            name='number_injured',
        ),
        migrations.RemoveField(
            model_name='accident',
            name='number_killed',
        ),
    ]
