# Generated by Django 6.0.4 on 2026-04-20 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0012_remove_accident_number_affected_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accidentchangelog',
            options={'ordering': ['-changed_at'], 'verbose_name': 'Accident change log', 'verbose_name_plural': 'Accident change logs'},
        ),
        migrations.RemoveField(
            model_name='accident',
            name='validated_at',
        ),
        migrations.AlterField(
            model_name='accident',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Brouillon'), ('SUBMITTED', 'Soumis'), ('TECH_VALIDATED', 'Validé techniquement'), ('PROGRAM_VALIDATED', 'Validé programme'), ('APPROVED', 'Approuvé'), ('TECH_REJECTED', 'Retourné au soumissionnaire'), ('PROGRAM_REJECTED', 'Retourné au validateur technique')], default='DRAFT', max_length=30, verbose_name='Statut'),
        ),
    ]
