# Generated by Django 6.0.4 on 2026-04-20 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0013_alter_accidentchangelog_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accident',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Brouillon'), ('SUBMITTED', 'Soumis'), ('TECH_VALIDATED', 'Validé techniquement'), ('PROGRAM_VALIDATED', 'Validé programme'), ('APPROVED', 'Approuvé')], default='DRAFT', max_length=30, verbose_name='Statut'),
        ),
    ]
