# Generated by Django 6.0.4 on 2026-05-08 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0014_alter_accident_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accident',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Brouillon'), ('SUBMITTED', 'Soumis'), ('TECH_VALIDATED', 'Validé techniquement'), ('PROGRAM_VALIDATED', 'Validé programme'), ('APPROVED', 'Approuvé'), ('RETURNED_FOR_CORRECTION', 'Retourné pour correction')], default='DRAFT', max_length=30, verbose_name='Statut'),
        ),
    ]
