# Generated by Django 6.0.4 on 2026-05-13 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0015_alter_accident_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accident',
            name='status',
            field=models.CharField(choices=[('SUBMITTED', 'Soumis'), ('TECH_VERIFIED', 'Vérification technique'), ('TECH_VALIDATED', 'Validation technique'), ('PROGRAM_VALIDATED', 'Validation programme'), ('APPROVED', 'Approuvé'), ('RETURNED_FOR_CORRECTION', 'Retourné pour correction')], default='SUBMITTED', max_length=30),
        ),
    ]
