# Generated by Django 6.0.4 on 2026-05-16 18:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0017_accident_tech_verified_at_accident_tech_verified_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='accident',
            name='tech_verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accidents_tech_verified', to=settings.AUTH_USER_MODEL, verbose_name='Vérifié techniquement par'),
        ),
    ]
